name: CI/CD

on:
  push:
  schedule:
  - cron:  '1 0 * * 0'

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      uses: docker/build-push-action@v1
      with:
        repository: pyhf/pyhf-validation-root-base
        dockerfile: Dockerfile
        tags: test
        tag_with_sha: true
        tag_with_ref: true
        push: false
    - name: List built images
      run: docker images
    - name: Check PATH
      run: |
        docker run --rm pyhf/pyhf-validation-root-base:test "which python;python --version;which root;root-config --version;hist2workspace --help"
        docker run --rm pyhf/pyhf-validation-root-base:test "which curl;which tar"
    - name: Run tests
      run: |
        docker run --rm -v $PWD:$PWD -w $PWD pyhf/pyhf-validation-root-base:test "python tests/rf308_normintegration2d.py"
        docker run --rm -v $PWD:$PWD -w $PWD pyhf/pyhf-validation-root-base:test "python -m pip install numpy; python tests/test_import_numpy_ROOT.py"
        docker run --rm -v $PWD:$PWD -w $PWD pyhf/pyhf-validation-root-base:test "python -m pip install numpy; python tests/test_import_ROOT_numpy.py"
